name: sunmi_printer_t1mini
description: A Flutter plugin for printing bills.
version: 0.0.6
homepage: https://github.com/Nik1308/SunmiPrinter

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  plugin:
    platforms:
      android:
        package: com.example.sunmi_printer_t1mini
        pluginClass: SunmiPrinterT1miniPlugin
      ios:
        pluginClass: SunmiPrinterT1miniPlugin

